name: 'Wiki Sync'
description: 'Sync a wiki folder with your GitHub Wiki'
author: 'JoeIzzard'
branding:
    icon: upload-cloud
    color: orange
inputs:
    username:
        description: 'The username of the repo owner'
        required: true
    access_token:
        description: 'The access token with Repo access. Can be passed in using `{{ secrets.GITHUB_TOKEN }}`.'
        required: true
    wiki_folder:
        description: 'The folder you want to sync the repo with'
        required: false
        default: 'wiki'
    ignore_safe_warnings:
        description: 'Fixes `fatal: detected dubious ownership in repository at /wiki`'
        required: false
        default: 'false'
    commit_message:
        description: 'A custom commit message to be used'
        required: false
        default: 'action: wiki sync'
    commit_username:
        description: 'The email address to use with the commit'
        required: true
    commit_email:
        description: 'The email address to use when committing'
        required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
